version: "3.4"

services:
  sallamation-server:
    image: sallamation-server
    ports:
      - "7108:80"

  sallamation-client:
    image: sallamation-client
    ports:
      - "7107:80"

  serverdb:
    container_name: serverdb
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ServerDb
    restart: always
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
